name = "cardano2vn/contract"
version = "0.0.0"
compiler = "v1.1.21"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'cardano2vn/contract'"

[repository]
user = "cardano2vn"
project = "contract"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[[dependencies]]
name = "sidan-lab/vodka"
version = "0.1.22"
source = "github"

[[dependencies]]
name = "logical-mechanism/assist"
version = "v0.5.1"
source = "github"

[config]
